version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mock_backend_db
    environment:
      POSTGRES_DB: mock_backend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mock_backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-backend:
    build: .
    container_name: mock_backend_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/mock_backend
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  postgres_data: