/**
 * Famous historical figures for agent names
 */
const agentNames = [
  // Famous Painters (30)
  "Da Vinci",
  "Michelangelo",
  "Rembrandt",
  "Caravaggio",
  "Vermeer",
  "Monet",
  "Van Gogh",
  "Renoir",
  "Cézanne",
  "Gauguin",
  "Matisse",
  "Picasso",
  "Dalí",
  "Kahlo",
  "Pollock",
  "Rothko",
  "Warhol",
  "Klimt",
  "Kandinsky",
  "Mondrian",
  "Manet",
  "Degas",
  "Toulouse-Lautrec",
  "Goya",
  "El Greco",
  "Velázquez",
  "Rubens",
  "Botticelli",
  "Raphael",
  "Titian",

  // Famous Composers (40)
  "Bach",
  "Mozart",
  "Beethoven",
  "Haydn",
  "Schubert",
  "Schumann",
  "Chopin",
  "Liszt",
  "Wagner",
  "Verdi",
  "Brahms",
  "Tchaikovsky",
  "Dvořák",
  "Grieg",
  "Mahler",
  "Strauss",
  "Debussy",
  "Ravel",
  "Rachmaninoff",
  "Stravinsky",
  "Prokofiev",
  "Shostakovich",
  "Bartók",
  "Vivaldi",
  "Handel",
  "Monteverdi",
  "Purcell",
  "Gluck",
  "Rossini",
  "Donizetti",
  "Bellini",
  "Puccini",
  "Berlioz",
  "Mendelssohn",
  "Bruckner",
  "Saint-Saëns",
  "Bizet",
  "Sibelius",
  "Elgar",
  "Vaughan Williams",

  // Famous Orchestra/Soloists (4)
  "Paganini",
  "Caruso",
  "Casals",
  "Heifetz",

  // Famous Architects (5)
  "Gaudí",
  "Wright",
  "Le Corbusier",
  "Palladio",
  "Brunelleschi",

  // Famous Movie Directors (30)
  "Hitchcock",
  "Kubrick",
  "Spielberg",
  "Scorsese",
  "Coppola",
  "Kurosawa",
  "Fellini",
  "Bergman",
  "Tarkovsky",
  "Godard",
  "Truffaut",
  "Buñuel",
  "Eisenstein",
  "Welles",
  "Wilder",
  "Hawks",
  "Ford",
  "Chaplin",
  "Keaton",
  "Lang",
  "Murnau",
  "Dreyer",
  "Ozu",
  "Mizoguchi",
  "Renoir",
  "De Sica",
  "Visconti",
  "Antonioni",
  "Pasolini",
  "Bresson",

  // Famous Actors (10)
  "Olivier",
  "Brando",
  "De Niro",
  "Pacino",
  "Stewart",
  "Grant",
  "Hepburn",
  "Davis",
  "Bergman",
  "Garbo",

  // Scientists, Inventors & Engineers - Physics (50)
  "Newton",
  "Einstein",
  "Galileo",
  "Kepler",
  "Faraday",
  "Maxwell",
  "Planck",
  "Bohr",
  "Heisenberg",
  "Schrödinger",
  "Dirac",
  "Fermi",
  "Feynman",
  "Oppenheimer",
  "Rutherford",
  "Curie",
  "Becquerel",
  "Thomson",
  "Boltzmann",
  "Carnot",
  "Joule",
  "Kelvin",
  "Clausius",
  "Gibbs",
  "Lorentz",
  "Poincaré",
  "Mach",
  "Hertz",
  "Rayleigh",
  "Wien",
  "Stefan",
  "Compton",
  "Millikan",
  "Michelson",
  "Morley",
  "Bragg",
  "Cavendish",
  "Coulomb",
  "Ampère",
  "Volta",
  "Ohm",
  "Kirchhoff",
  "Weber",
  "Helmholtz",
  "Huygens",
  "Fresnel",
  "Young",
  "Röntgen",
  "Zeeman",
  "Stark",

  // Math (50)
  "Euclid",
  "Archimedes",
  "Pythagoras",
  "Gauss",
  "Euler",
  "Riemann",
  "Cauchy",
  "Lagrange",
  "Laplace",
  "Fourier",
  "Fermat",
  "Pascal",
  "Leibniz",
  "Descartes",
  "Bernoulli",
  "Weierstrass",
  "Cantor",
  "Dedekind",
  "Kronecker",
  "Hilbert",
  "Poincaré",
  "Noether",
  "Gödel",
  "Turing",
  "Von Neumann",
  "Kolmogorov",
  "Ramanujan",
  "Hardy",
  "Littlewood",
  "Erdős",
  "Klein",
  "Lie",
  "Cayley",
  "Hamilton",
  "Jacobi",
  "Legendre",
  "Chebyshev",
  "Markov",
  "Galois",
  "Abel",
  "Dirichlet",
  "Liouville",
  "Borel",
  "Lebesgue",
  "Fréchet",
  "Hausdorff",
  "Banach",
  "Wiener",
  "Shannon",
  "Nash",

  // Biology (40)
  "Darwin",
  "Mendel",
  "Pasteur",
  "Koch",
  "Fleming",
  "Lister",
  "Jenner",
  "Harvey",
  "Linnaeus",
  "Lamarck",
  "Wallace",
  "Huxley",
  "Crick",
  "Watson",
  "Franklin",
  "McClintock",
  "Morgan",
  "Pavlov",
  "Loewi",
  "Sherrington",
  "Cajal",
  "Golgi",
  "Virchow",
  "Schwann",
  "Schleiden",
  "Hooke",
  "Leeuwenhoek",
  "Malpighi",
  "Vesalius",
  "Galen",
  "Hippocrates",
  "Avery",
  "Beadle",
  "Tatum",
  "Lederberg",
  "Delbrück",
  "Lwoff",
  "Monod",
  "Jacob",
  "Brenner",

  // AI & Computer Science (60)
  "Turing",
  "Von Neumann",
  "Shannon",
  "Wiener",
  "McCarthy",
  "Minsky",
  "Newell",
  "Simon",
  "Dijkstra",
  "Knuth",
  "Hoare",
  "Floyd",
  "Cook",
  "Karp",
  "Rivest",
  "Shamir",
  "Adleman",
  "Diffie",
  "Hellman",
  "Lamport",
  "Liskov",
  "Thompson",
  "Ritchie",
  "Kernighan",
  "Torvalds",
  "Stallman",
  "Kay",
  "Engelbart",
  "Licklider",
  "Sutherland",
  "Brooks",
  "Codd",
  "Date",
  "Bachman",
  "Lovelace",
  "Babbage",
  "Hopper",
  "Backus",
  "Chomsky",
  "Aho",
  "Ullman",
  "Tarjan",
  "Perlis",
  "Rabin",
  "Scott",
  "Milner",
  "Strachey",
  "Naur",
  "Dahl",
  "Nygaard",
  "Wirth",
  "Dijkstra",
  "Parnas",
  "Yourdon",
  "DeMarco",
  "Boehm",
  "Hinton",
  "LeCun",
  "Bengio",
  "Ng",

  // Famous Video Game Directors (10)
  "Miyamoto",
  "Kojima",
  "Meier",
  "Wright",
  "Molyneux",
  "Carmack",
  "Romero",
  "Schafer",
  "Levine",
  "Cage",

  // Conquerors & Leaders (pre-20th century + Churchill, De Gaulle, mid-century US presidents)
  "Alexander",
  "Caesar",
  "Hannibal",
  "Genghis Khan",
  "Attila",
  "Charlemagne",
  "Napoleon",
  "Saladin",
  "Tamerlane",
  "Cyrus",
  "Ramesses",
  "Leonidas",
  "Scipio",
  "Pompey",
  "Octavian",
  "Trajan",
  "Constantine",
  "Justinian",
  "Belisarius",
  "Suleiman",
  "Akbar",
  "Peter the Great",
  "Marlborough",
  "Wellington",
  "Nelson",
  "Churchill",
  "De Gaulle",
  "Truman",
  "Eisenhower",
  "Kennedy",

  // Philosophers (20)
  "Socrates",
  "Plato",
  "Aristotle",
  "Confucius",
  "Lao Tzu",
  "Epicurus",
  "Seneca",
  "Marcus Aurelius",
  "Aquinas",
  "Descartes",
  "Spinoza",
  "Leibniz",
  "Locke",
  "Hume",
  "Kant",
  "Hegel",
  "Schopenhauer",
  "Nietzsche",
  "Kierkegaard",
  "Wittgenstein",

  // Other Nobel Prizes (historical, 10)
  "Beckett",
  "Hemingway",
  "Faulkner",
  "Steinbeck",
  "Churchill",
  "Russell",
  "Schweitzer",
  "Marshall",
  "Pauling",
  "King",

  // Famous Women (30)
  "Cleopatra",
  "Joan",
  "Catherine",
  "Victoria",
  "Parks",
  "Curie",
  "Lovelace",
  "Rosalind Franklin",
  "Hopper",
  "Nightingale",
  "Jane Austen",
  "Woolf",
  "Dickinson",
  "De Beauvoir",
  "Arendt",
  "Wollstonecraft",
  "Kahlo",
  "O'Keeffe",
  "Gentileschi",
  "Chanel",
  "Earhart",
  "Hatshepsut",
  "Zetian",
  "Hypatia",
  "Noether",
  "Kovalevsky",

  // The team (2)
  "Nougaret",
  "Makarov",
  "Cloarec",
  "Kyrylo",

  // Business
  "Gates",
  "Jobs",
  "Bezos",
  "Elon",
  "Holz",
  "Amodei",
  "Altman",

  // ML
  "Hinton",
  "LeCun",
  "Bengio",
  "Ng",
  "Hassabis",
  "Li",
  "Goodfellow",
  "Pearl",
  "Russell",
  "Norvig",
  "Koller",
  "Jordan",
  "Sutskever",
  "Karpathy",
  "Manning",
  "Lee",
  "Etzioni",
  "Tegmark",
  "Marcus",
  "Breazeal",
  "Brooks",
  "Thrun",
  "Schmidhuber"
];

/**
 * Generates a random famous person's name for agent display name
 * @returns A famous historical figure's name
 */
export function generateAgentName(): string {
  return agentNames[Math.floor(Math.random() * agentNames.length)];
}

/**
 * Generates a creative branch name with agent ID suffix
 * @param agentId The agent's UUID
 * @returns The formatted branch name (e.g., "quantum-entangling-einstein-a1b2")
 */
export function generateAgentBranchName(agentId: string, agentName: string): string {
  const prefix = agentName.toLowerCase().split(" ").join("-");
  const shortId = agentId.substring(0, 4);
  return `ariana/${prefix}-${shortId}`;
}